// src/components/Button/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react'
import spinnerLight from '../../assets/spinner-light.svg'
import spinnerDark from '../../assets/spinner-dark.svg'
import './Button.css'

export type ButtonVariant = 'primary' | 'secondary' | 'ghost'
export type ButtonSize = 'sm' | 'md' | 'lg'

export type ButtonProps = {
  children?: ReactNode
  variant?: ButtonVariant
  size?: ButtonSize
  loading?: boolean
} & Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'children'>

export function Button({
  children = 'Button',
  variant = 'primary',
  size = 'md',
  loading = false,
  disabled = false,
  className = '',
  type = 'button',
  ...rest
}: ButtonProps) {
  const isDisabled = disabled || loading
  const spinnerSrc = variant === 'primary' ? spinnerLight : spinnerDark

  return (
    <button
      type={type}
      className={['btn', `btn--${variant}`, `btn--${size}`, className]
        .filter(Boolean)
        .join(' ')}
      disabled={isDisabled}
      aria-busy={loading || undefined}
      data-loading={loading || undefined}
      {...rest}
    >
      {loading ? (
        <img
          className="btn__spinner"
          src={spinnerSrc}
          alt=""
          aria-hidden="true"
          width={size === 'sm' ? 14 : size === 'md' ? 16 : 20}
          height={size === 'sm' ? 14 : size === 'md' ? 16 : 20}
        />
      ) : null}
      <span className="btn__label">{children}</span>
    </button>
  )
}

// src/frameworks/angular/button/button.component.ts
import { Component, Input } from '@angular/core'
import { NgIf } from '@angular/common'

export type ButtonVariant = 'primary' | 'secondary' | 'ghost'
export type ButtonSize = 'sm' | 'md' | 'lg'

/**
 * Bonico Button — Angular (standalone)
 * Visual parity with the React Button. Uses the same CSS tokens from `src/tokens/tokens.css`.
 */
@Component({
  selector: 'bonico-button',
  standalone: true,
  imports: [NgIf],
  templateUrl: './button.component.html',
  styleUrl: './button.component.css',
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary'
  @Input() size: ButtonSize = 'md'
  @Input() loading = false
  @Input() disabled = false
  @Input() type: 'button' | 'submit' | 'reset' = 'button'
  @Input() label = 'Button'

  get isDisabled(): boolean {
    return this.disabled || this.loading
  }

  get hostClass(): string {
    return ['btn', `btn--${this.variant}`, `btn--${this.size}`].join(' ')
  }

  get spinnerSrc(): string {
    return this.variant === 'primary'
      ? 'assets/spinner-light.svg'
      : 'assets/spinner-dark.svg'
  }

  get spinnerSize(): number {
    if (this.size === 'sm') return 14
    if (this.size === 'lg') return 20
    return 16
  }
}

<button
  [attr.type]="type"
  [class]="hostClass"
  [disabled]="isDisabled"
  [attr.aria-busy]="loading || null"
  [attr.data-loading]="loading || null"
>
  <img
    *ngIf="loading"
    class="btn__spinner"
    [src]="spinnerSrc"
    alt=""
    aria-hidden="true"
    [attr.width]="spinnerSize"
    [attr.height]="spinnerSize"
  />
  <span class="btn__label">{{ label }}</span>
</button>
